/**
 * @fileoverview gRPC-Web generated client stub for protosound
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: proto.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.protosound = require('./proto_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.protosound.SoundServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.protosound.SoundServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protosound.ClientInfoMessage,
 *   !proto.protosound.ChatServerMessage>}
 */
const methodDescriptor_SoundService_GetSound = new grpc.web.MethodDescriptor(
  '/protosound.SoundService/GetSound',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.protosound.ClientInfoMessage,
  proto.protosound.ChatServerMessage,
  /**
   * @param {!proto.protosound.ClientInfoMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protosound.ChatServerMessage.deserializeBinary
);


/**
 * @param {!proto.protosound.ClientInfoMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.protosound.ChatServerMessage>}
 *     The XHR Node Readable Stream
 */
proto.protosound.SoundServiceClient.prototype.getSound =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/protosound.SoundService/GetSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_GetSound);
};


/**
 * @param {!proto.protosound.ClientInfoMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.protosound.ChatServerMessage>}
 *     The XHR Node Readable Stream
 */
proto.protosound.SoundServicePromiseClient.prototype.getSound =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/protosound.SoundService/GetSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_GetSound);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protosound.ChatClientMessage,
 *   !proto.protosound.ClientResponseMessage>}
 */
const methodDescriptor_SoundService_SendSound = new grpc.web.MethodDescriptor(
  '/protosound.SoundService/SendSound',
  grpc.web.MethodType.UNARY,
  proto.protosound.ChatClientMessage,
  proto.protosound.ClientResponseMessage,
  /**
   * @param {!proto.protosound.ChatClientMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protosound.ClientResponseMessage.deserializeBinary
);


/**
 * @param {!proto.protosound.ChatClientMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protosound.ClientResponseMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protosound.ClientResponseMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protosound.SoundServiceClient.prototype.sendSound =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protosound.SoundService/SendSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSound,
      callback);
};


/**
 * @param {!proto.protosound.ChatClientMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protosound.ClientResponseMessage>}
 *     Promise that resolves to the response
 */
proto.protosound.SoundServicePromiseClient.prototype.sendSound =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protosound.SoundService/SendSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSound);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protosound.ClientInfoMessage,
 *   !proto.protosound.EmptyMessage>}
 */
const methodDescriptor_SoundService_PingServer = new grpc.web.MethodDescriptor(
  '/protosound.SoundService/PingServer',
  grpc.web.MethodType.UNARY,
  proto.protosound.ClientInfoMessage,
  proto.protosound.EmptyMessage,
  /**
   * @param {!proto.protosound.ClientInfoMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protosound.EmptyMessage.deserializeBinary
);


/**
 * @param {!proto.protosound.ClientInfoMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protosound.EmptyMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protosound.EmptyMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protosound.SoundServiceClient.prototype.pingServer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protosound.SoundService/PingServer',
      request,
      metadata || {},
      methodDescriptor_SoundService_PingServer,
      callback);
};


/**
 * @param {!proto.protosound.ClientInfoMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protosound.EmptyMessage>}
 *     Promise that resolves to the response
 */
proto.protosound.SoundServicePromiseClient.prototype.pingServer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protosound.SoundService/PingServer',
      request,
      metadata || {},
      methodDescriptor_SoundService_PingServer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protosound.EmptyMessage,
 *   !proto.protosound.ClientUserInitResponseMessage>}
 */
const methodDescriptor_SoundService_InitUser = new grpc.web.MethodDescriptor(
  '/protosound.SoundService/InitUser',
  grpc.web.MethodType.UNARY,
  proto.protosound.EmptyMessage,
  proto.protosound.ClientUserInitResponseMessage,
  /**
   * @param {!proto.protosound.EmptyMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protosound.ClientUserInitResponseMessage.deserializeBinary
);


/**
 * @param {!proto.protosound.EmptyMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protosound.ClientUserInitResponseMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protosound.ClientUserInitResponseMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protosound.SoundServiceClient.prototype.initUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protosound.SoundService/InitUser',
      request,
      metadata || {},
      methodDescriptor_SoundService_InitUser,
      callback);
};


/**
 * @param {!proto.protosound.EmptyMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protosound.ClientUserInitResponseMessage>}
 *     Promise that resolves to the response
 */
proto.protosound.SoundServicePromiseClient.prototype.initUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protosound.SoundService/InitUser',
      request,
      metadata || {},
      methodDescriptor_SoundService_InitUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protosound.EmptyMessage,
 *   !proto.protosound.ClientConfInitResponseMessage>}
 */
const methodDescriptor_SoundService_InitConf = new grpc.web.MethodDescriptor(
  '/protosound.SoundService/InitConf',
  grpc.web.MethodType.UNARY,
  proto.protosound.EmptyMessage,
  proto.protosound.ClientConfInitResponseMessage,
  /**
   * @param {!proto.protosound.EmptyMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protosound.ClientConfInitResponseMessage.deserializeBinary
);


/**
 * @param {!proto.protosound.EmptyMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protosound.ClientConfInitResponseMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protosound.ClientConfInitResponseMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protosound.SoundServiceClient.prototype.initConf =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protosound.SoundService/InitConf',
      request,
      metadata || {},
      methodDescriptor_SoundService_InitConf,
      callback);
};


/**
 * @param {!proto.protosound.EmptyMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protosound.ClientConfInitResponseMessage>}
 *     Promise that resolves to the response
 */
proto.protosound.SoundServicePromiseClient.prototype.initConf =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protosound.SoundService/InitConf',
      request,
      metadata || {},
      methodDescriptor_SoundService_InitConf);
};


module.exports = proto.protosound;

