# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_pb2 as proto__pb2


class SoundServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSound = channel.unary_stream(
                '/protoSound.SoundService/GetSound',
                request_serializer=proto__pb2.ClientInfoMessage.SerializeToString,
                response_deserializer=proto__pb2.ChatServerMessage.FromString,
                )
        self.SendSound = channel.unary_unary(
                '/protoSound.SoundService/SendSound',
                request_serializer=proto__pb2.ChatClientMessage.SerializeToString,
                response_deserializer=proto__pb2.ClientResponseMessage.FromString,
                )
        self.InitUser = channel.unary_unary(
                '/protoSound.SoundService/InitUser',
                request_serializer=proto__pb2.EmptyMessage.SerializeToString,
                response_deserializer=proto__pb2.ClientUserInitResponseMessage.FromString,
                )
        self.InitConf = channel.unary_unary(
                '/protoSound.SoundService/InitConf',
                request_serializer=proto__pb2.EmptyMessage.SerializeToString,
                response_deserializer=proto__pb2.ClientConfInitResponseMessage.FromString,
                )


class SoundServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitConf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSound': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSound,
                    request_deserializer=proto__pb2.ClientInfoMessage.FromString,
                    response_serializer=proto__pb2.ChatServerMessage.SerializeToString,
            ),
            'SendSound': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSound,
                    request_deserializer=proto__pb2.ChatClientMessage.FromString,
                    response_serializer=proto__pb2.ClientResponseMessage.SerializeToString,
            ),
            'InitUser': grpc.unary_unary_rpc_method_handler(
                    servicer.InitUser,
                    request_deserializer=proto__pb2.EmptyMessage.FromString,
                    response_serializer=proto__pb2.ClientUserInitResponseMessage.SerializeToString,
            ),
            'InitConf': grpc.unary_unary_rpc_method_handler(
                    servicer.InitConf,
                    request_deserializer=proto__pb2.EmptyMessage.FromString,
                    response_serializer=proto__pb2.ClientConfInitResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoSound.SoundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SoundService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protoSound.SoundService/GetSound',
            proto__pb2.ClientInfoMessage.SerializeToString,
            proto__pb2.ChatServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendSound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoSound.SoundService/SendSound',
            proto__pb2.ChatClientMessage.SerializeToString,
            proto__pb2.ClientResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoSound.SoundService/InitUser',
            proto__pb2.EmptyMessage.SerializeToString,
            proto__pb2.ClientUserInitResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitConf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoSound.SoundService/InitConf',
            proto__pb2.EmptyMessage.SerializeToString,
            proto__pb2.ClientConfInitResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
