# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\x12\nprotosound\"W\n\x11\x43hatServerMessage\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\x12\x0c\n\x04rate\x18\x02 \x01(\x03\x12\x0f\n\x07soundId\x18\x04 \x01(\x04\x12\x0f\n\x07onlyOne\x18\x05 \x01(\x08J\x04\x08\x01\x10\x02\"\x88\x01\n\x11\x43hatClientMessage\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x02\x12\x0c\n\x04rate\x18\x02 \x01(\x03\x12\x0e\n\x06userId\x18\x06 \x01(\r\x12\x0e\n\x06\x63onfId\x18\x07 \x01(\x04\x12\x11\n\ttimeStamp\x18\x08 \x01(\x04\x12\x12\n\nmessageInd\x18\t \x01(\rJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06\"J\n\x15\x43lientResponseMessage\x12\x0c\n\x04rate\x18\x01 \x01(\x03\x12\x0f\n\x07soundId\x18\x02 \x01(\x04\x12\x12\n\nmessageInd\x18\x03 \x01(\r\"3\n\x11\x43lientInfoMessage\x12\x0e\n\x06\x63onfId\x18\x01 \x01(\x04\x12\x0e\n\x06userId\x18\x02 \x01(\r\"/\n\x1d\x43lientUserInitResponseMessage\x12\x0e\n\x06userId\x18\x01 \x01(\r\"/\n\x1d\x43lientConfInitResponseMessage\x12\x0e\n\x06\x63onfId\x18\x01 \x01(\x04\"\x0e\n\x0c\x45mptyMessage2\x92\x03\n\x0cSoundService\x12J\n\x08GetSound\x12\x1d.protosound.ClientInfoMessage\x1a\x1d.protosound.ChatServerMessage0\x01\x12M\n\tSendSound\x12\x1d.protosound.ChatClientMessage\x1a!.protosound.ClientResponseMessage\x12\x45\n\nPingServer\x12\x1d.protosound.ClientInfoMessage\x1a\x18.protosound.EmptyMessage\x12O\n\x08InitUser\x12\x18.protosound.EmptyMessage\x1a).protosound.ClientUserInitResponseMessage\x12O\n\x08InitConf\x12\x18.protosound.EmptyMessage\x1a).protosound.ClientConfInitResponseMessageB\x0fZ\r./;protosoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./;protosound'
  _globals['_CHATSERVERMESSAGE']._serialized_start=27
  _globals['_CHATSERVERMESSAGE']._serialized_end=114
  _globals['_CHATCLIENTMESSAGE']._serialized_start=117
  _globals['_CHATCLIENTMESSAGE']._serialized_end=253
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_start=255
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_end=329
  _globals['_CLIENTINFOMESSAGE']._serialized_start=331
  _globals['_CLIENTINFOMESSAGE']._serialized_end=382
  _globals['_CLIENTUSERINITRESPONSEMESSAGE']._serialized_start=384
  _globals['_CLIENTUSERINITRESPONSEMESSAGE']._serialized_end=431
  _globals['_CLIENTCONFINITRESPONSEMESSAGE']._serialized_start=433
  _globals['_CLIENTCONFINITRESPONSEMESSAGE']._serialized_end=480
  _globals['_EMPTYMESSAGE']._serialized_start=482
  _globals['_EMPTYMESSAGE']._serialized_end=496
  _globals['_SOUNDSERVICE']._serialized_start=499
  _globals['_SOUNDSERVICE']._serialized_end=901
# @@protoc_insertion_point(module_scope)
