/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: proto.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.proto = require('./proto_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.SoundServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.SoundServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ChatClientMessage,
 *   !proto.proto.ChatServerMessage>}
 */
const methodDescriptor_SoundService_GetSoundJustHello = new grpc.web.MethodDescriptor(
  '/proto.SoundService/GetSoundJustHello',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.proto.ChatClientMessage,
  proto.proto.ChatServerMessage,
  /**
   * @param {!proto.proto.ChatClientMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.ChatServerMessage.deserializeBinary
);


/**
 * @param {!proto.proto.ChatClientMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ChatServerMessage>}
 *     The XHR Node Readable Stream
 */
proto.proto.SoundServiceClient.prototype.getSoundJustHello =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/proto.SoundService/GetSoundJustHello',
      request,
      metadata || {},
      methodDescriptor_SoundService_GetSoundJustHello);
};


/**
 * @param {!proto.proto.ChatClientMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ChatServerMessage>}
 *     The XHR Node Readable Stream
 */
proto.proto.SoundServicePromiseClient.prototype.getSoundJustHello =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/proto.SoundService/GetSoundJustHello',
      request,
      metadata || {},
      methodDescriptor_SoundService_GetSoundJustHello);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ChatClientMessage,
 *   !proto.proto.ChatServerMessage>}
 */
const methodDescriptor_SoundService_GetSound = new grpc.web.MethodDescriptor(
  '/proto.SoundService/GetSound',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.proto.ChatClientMessage,
  proto.proto.ChatServerMessage,
  /**
   * @param {!proto.proto.ChatClientMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.ChatServerMessage.deserializeBinary
);


/**
 * @param {!proto.proto.ChatClientMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ChatServerMessage>}
 *     The XHR Node Readable Stream
 */
proto.proto.SoundServiceClient.prototype.getSound =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/proto.SoundService/GetSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_GetSound);
};


/**
 * @param {!proto.proto.ChatClientMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ChatServerMessage>}
 *     The XHR Node Readable Stream
 */
proto.proto.SoundServicePromiseClient.prototype.getSound =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/proto.SoundService/GetSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_GetSound);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ChatClientMessage,
 *   !proto.proto.EmptyMessage>}
 */
const methodDescriptor_SoundService_SendSound = new grpc.web.MethodDescriptor(
  '/proto.SoundService/SendSound',
  grpc.web.MethodType.UNARY,
  proto.proto.ChatClientMessage,
  proto.proto.EmptyMessage,
  /**
   * @param {!proto.proto.ChatClientMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.EmptyMessage.deserializeBinary
);


/**
 * @param {!proto.proto.ChatClientMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.EmptyMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.EmptyMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.SoundServiceClient.prototype.sendSound =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.SoundService/SendSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSound,
      callback);
};


/**
 * @param {!proto.proto.ChatClientMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.EmptyMessage>}
 *     Promise that resolves to the response
 */
proto.proto.SoundServicePromiseClient.prototype.sendSound =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.SoundService/SendSound',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSound);
};


module.exports = proto.proto;

